[project]
name = "pyrmm"
version = "0.1.0"
description = "用来新建和管理,开发magisk模块的工具集"
readme = "README.md"
authors = [
    { name = "LIghtJUNction", email = "LIghtJUNction.me@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "toml>=0.10.2",
]

[project.scripts]
rmm = "pyrmm.cli.__main__:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

