[package]
name = "basic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "basic"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24.0"
chrono = { version = "0.4", features = ["serde"] }
