id = "test-fs"
name = "test-fs"
requires_rmm = ">=0.1.0"
versionCode = "C:\\Users\\light\\Documents\\GitHub\\RootManageModuleModel\\test-fs"
updateJson = "https://raw.githubusercontent.com/LIghtJUNction/test-fs/main/update.json"
readme = "README.MD"
changelog = "CHANGELOG.MD"
lecense = "LICENSE"
[[dependencies]]
"dep?" = "?version"

[[authors]]
name = "LIghtJUNction"
email = "email"

[[scripts]]
build = "rmm build"

[urls]
github = "https://github.com/LIghtJUNction/test-fs"

[git]
git_root = "C:\\Users\\light\\Documents\\GitHub\\RootManageModuleModel"
remote_url = "https://github.com/LIghtJUNction/RootManageModuleModel.git"
username = "LIghtJUNction"
repo_name = "RootManageModuleModel"
is_in_repo_root = "False"
