name: initial

on:
  workflow_dispatch:
    inputs:
      id:
        description: '请输入模块id，例如Zygisk_shamiko'
        required: true
      
      name:
        description: '请输入模块名，例如shamiko'
        required: true

      author:
        description: '作者名'
        required: true

      description:
        description: '模块描述'
        required: true


jobs:
  rename:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:  
          ref: main  

      - name: Check if directory exists & clear it
        run: |
          if [ -d "Mymodule/module.prop" ]; then
          echo "Directory exists."
          echo "" > Mymodule/module.prop
          else
            echo "Directory does not exist."
            echo "" > ${{ github.event.inputs.id }}/module.prop
          fi



      - name: Get Version
        id: get_version
        run: |
          echo "date=$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"

      - name: Rename "MyModule" folder
        if: ${{ github.event.inputs.id != 'MyModule'  }}
        run: |
          mv MyModule ${{ github.event.inputs.id }}


      - name: Add the id key in the file
        run: |
          echo "id=${{ github.event.inputs.id }}" >> ${{ github.event.inputs.id }}/module.prop
      - name: Add the name key in the file
        run: |
          echo "name=${{ github.event.inputs.name }}" >> ${{ github.event.inputs.id }}/module.prop

      - name: Add the version key in the file
        run: |
          echo "version=0.0.1" >> ${{ github.event.inputs.id }}/module.prop

      - name: Add the version code key in the file
        run: |
          echo "versionCode=${{ steps.get_version.outputs.date }}" >> ${{ github.event.inputs.id }}/module.prop

      - name: Add the author key in the file
        run: |
          echo "author=${{ github.event.inputs.author }}" >> ${{ github.event.inputs.id }}/module.prop

      - name: Add the description key in the file
        run: |
          echo "description=${{ github.event.inputs.description }}" >> ${{ github.event.inputs.id }}/module.prop

      - name: List files for debug
        run: ls -la



      - name: Debugging Output
        run: |
          git status
          git log -1


      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Rename module folder to ${{ github.event.inputs.id }} and update module.prop"
          git push origin main

