name: initial

on:
  workflow_dispatch:
    inputs:
      module_name:
        description: 'Enter the module name'
        required: true

jobs:
  rename_module:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Rename "my module" folder
        run: |
          mv "my module" "${{ github.event.inputs.module_name }}"

      - name: Update the name key in the file
        run: |
          echo "name=${{ github.event.inputs.module_name }}" >> your_file.txt

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Rename module folder to ${{ github.event.inputs.module_name }} and update name key"
          git push origin master
