name: Multi-Platform Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          # x86_64 platforms
          - os: ubuntu-latest
            arch: x86_64
          - os: windows-latest
            arch: x86_64
          - os: macos-latest
            arch: x86_64
          # ARM64 platforms (GitHub Actions supported)
          - os: ubuntu-latest
            arch: arm64          
          - os: macos-latest
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup CMake
      uses: threeal/cmake-action@v2.1.0
      with:
        run-build: false

    - name: Setup uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.12"
        enable-cache: true

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.arch == 'arm64' && 'aarch64-unknown-linux-gnu' || '' }}

    - name: Install cross compilation tools (ARM64)
      if: matrix.arch == 'arm64' && matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu
    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          rust/target/
        key: ${{ runner.os }}-${{ matrix.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache uv dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          .venv
        key: ${{ runner.os }}-${{ matrix.arch }}-uv-${{ hashFiles('uv.lock') }}

    - name: Configure git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Sync dependencies
      run: uv sync

    - name: Install build tools
      run: |
        uv add --dev maturin
        uv add --dev build

    - name: Build wheel with maturin
      run: uv run maturin build --release

    - name: Commit changes (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        git add .
        if ! git diff --cached --quiet; then
          git commit -m "Build for ${{ matrix.os }}"
        else
          echo "No changes to commit"
        fi

    - name: Commit changes (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        git add .
        $status = git status --porcelain
        if ($status) {
          git commit -m "Build for ${{ matrix.os }}"
        } else {
          Write-Host "No changes to commit"
        }

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}
        path: |
          dist/
          rust/target/wheels/
        retention-days: 7

  push-changes:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Pull latest changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull origin main

    - name: Push changes
      run: |
        if git log origin/main..HEAD --oneline | grep -q .; then
          git push origin main
        else
          echo "No new commits to push"
        fi
