name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag(一般就填版本号)'
        required: true     

      id:
        description: '模块id'
        required: true     
      name:
        description: '模块名'
        required: true     




jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
        with:  
          ref: main  

      - name: Get Repository URL
        id: get_repo_url
        run: |
          echo "repo_url=https://github.com/${{ github.repository }}" >> "$GITHUB_ENV"
    
      - name: Get Version
        id: get_version
        run: |
          echo "date=$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"

      - name: Update update.json and module.prop
        run: |
          echo '{
            "version": "${{ github.event.inputs.tag }}",
            "versionCode": "${{ steps.get_version.outputs.date }}",
            "zipUrl": "${{ env.repo_url }}/releases/download/${{ github.event.inputs.tag }}/${{github.event.inputs.name }}-${{ github.event.inputs.tag }}.zip",
            "changelog": "${{ env.repo_url }}/raw/main/CHANGELOG.md"
          }' > update.json

          sed -i "s/$(grep -oP 'version=\K[^ ]+' module.prop)/${{ github.event.inputs.tag }}/g" main/MyModule/module.prop
          sed -i "s/$(grep -oP 'versionCode=\K[^ ]+' module.prop)/$(date +%Y%m%d)/g" main/MyModule/module.prop

      - name: run build.sh
        run: |
          sh build.sh
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: | 
           ${{ github.event.inputs.name }}-*.zip 

          generate_release_note: true
